packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@shopify/react-native-skia'
  - sharp
  - unrs-resolver

patchedDependencies:
  expo-better-auth-passkey@1.4.3: patches/expo-better-auth-passkey@1.4.3.patch
